### ISSUE TITLE
Rebuild with CUDA 12.5

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/slepc-feedstock#83]
As [CUDA 12.5 recently came out]( https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html ) and is being published to conda-forge ( https://github.com/conda-forge/cuda-feedstock/issues/29 ), it may make sense to rebuild SLEPc with it to pick up the latest features

Imagine this will be pretty similar to what was done for CUDA 12.4: https://github.com/conda-forge/slepc-feedstock/pull/80

**Comment by minrk** [comment]
currently building with 12.6
